### ISSUE TITLE
Cannot import name sgd

### ISSUE THREAD

**Issue by umbertoDifa** [flaviovdf/fpmc#5]
Hi @flaviovdf,

do you know why I get : Cannot import name 'sgd' when running the main file?
Indeed no module named sgd is generated during the setup.

Thanks,

Umberto

**Comment by flaviovdf** [comment]
Can you post the stack trace and how you are running the code? Also, are you executing it from the project folder?

**Comment by umbertoDifa** [comment]
Hi, thanks for answering.
This is the error:
![selection_001](https://cloud.githubusercontent.com/assets/3491592/23628580/01a3d2ce-02b5-11e7-86ed-f4259f0fd9c1.png)
I am running the main.py from the very same folder the main.py is saved. Also in the picture the error is about the dataio module, I fixed that by adding the line
`from fpmc import dataio` in the __init__.py file.
Anyway after fixing that I get the same error about the sgd module, but this time I don't know how to fix this.
Am I supposed to have an sgd.py file somewhere?

Thanks,
Umberto

**Comment by flaviovdf** [comment]
After compiling (make), please try:

```
PYTHONPATH=. python main.py data.txt 3 model.hr5
```

**Comment by umbertoDifa** [comment]
It still gives me the same error. Thanks anyways!

**Comment by ghost** [comment]
Hey looks like when you use make it creates .so files with strange names and they do not match the normal ones. e.g., fpmc.cpython-35m-x86_64-linux-gnu.so. I had to add fpmc.so in addition to them and use sudo python main.py ... in order to get the code to work. Perhaps this might help.
